### ISSUE TITLE
Clarify Windows only status

### ISSUE THREAD

**Issue by underscorediscovery** [RichieSams/FiberTaskingLib#1]
Ideally in the readme, somewhere obvious :)

Seems like the basis for a useful library so far though :+1:

**Comment by RichieSams** [comment]
Addressed in commit 1bb22997d2de490c0647cfa7ba839a7b061e65ee

**Comment by underscorediscovery** [comment]
With regards to other platforms API's, starting with `pthreads` is a good option, and definitely possible/easy.

It covers many platforms (*nix based, OS X, iOS, Android) etc. I have seen pthreads implementations on Windows, so you could start there if it's easier to develop against for your workflow.

pthread_attr_* functions are how you generally go about this, 
There are quite a lot of coroutines/fibers implementations written about pthreads, and quite a few libraries that are viral licensed - so be aware when looking into their implementation details. 

I've already been tinkering with fibers on pthreads, so when I've had a closer look into the current implementation here I may be able to look into it further in regards to this library.

**Comment by underscorediscovery** [comment]
@RichieSams any thoughts on this? The readme is now further convoluting the nature of fibers on other platforms.

**Comment by RichieSams** [comment]
I'm in the process of adding support for other platforms through Boost.Context. The code is already in the repo if you want to check it out. 

I haven't updated the readme yet because the code is still a bit brittle. (I would like to implement the tests I already have as well as add some more). Also, I'm teaching myself pthreads as I go, so I'm still a bit wary. 

In my opinion, trying to run fibers on top of pthreads sort of defeats the whole purpose of using fibers for task based multitasking. Pthreads have no innate way to cooperatively multitask, so you would have to switch between them with synchronization primitives. And would still incur a context switch. In the end, it would probably be easier and simpler to just use the chaining / work stealing model of TBB.

**Comment by RichieSams** [comment]
I tried to clarify the supported platforms here: de8f1f28143f6e744e338c99b1c70ad4aef514d8
