### ISSUE TITLE
std::atomic_signal_fence use

### ISSUE THREAD

**Issue by martty** [RichieSams/FiberTaskingLib#137]
std::atomic_signal_fence is used to achieve a memory barrier within a thread (so just a compiler barrier), but we are using it for inter-thread synchronization (on x86), to make our non-atomic accesses visible to other threads. This I think is incorrect.

https://stackoverflow.com/questions/14581090/how-to-correctly-use-stdatomic-signal-fence
https://stackoverflow.com/questions/18449291/when-is-a-compiler-only-memory-barrier-such-as-stdatomic-signal-fence-useful

**Comment by martty** [comment]
I think this also a problem because this fence is the only thing that makes (or would make ) the following thing work:

```
int i = 3;
scheduler->AddTask([&i](){ assert(i == 3; });
```

**Comment by RichieSams** [comment]
Sorry. I'm not ghosting you. I will take a look thia weekend. Thanks for the report!

**Comment by RichieSams** [comment]
So, in the `WaitFreeQueue`, we use `atomic_signal_fence` / `atomic_thread_fence`, to protect the reads / writes of the queue member variables. According to (https://hal.inria.fr/hal-00802885/document) for strong memory model CPUs like x86 and x64, we can get away with only `atomic_signal_fence`, since the memory model itself enforces the correct ordering, due to how the data depends on each other. (IE, the `m_bottom.store(b + 1, std::memory_order_relaxed);`, depends on b being read already, so the CPU will already force that ordering.

However, in our case, we would like to guarantee ordering constraints around `AddTask(s)`, and the subsequent running of the task.

I think, for this we have two options:

1. Add our own fences.
    * We would need a `release` fence at the start of `AddTask(s)`
    * This would force all writes done by the user to be visible to the other threads
    * Then we would need an `acquire` fence before [this line](https://github.com/RichieSams/FiberTaskingLib/blob/master/source/task_scheduler.cpp#L197)
2. Force the memory barriers in WaitFreeQueue to always be `atomic_thread_fence(std::memory_order_cst)`
    * We'd want to make a note at the top that we're deviating from `'Correct and Efficient Work-Stealing for Weak Memory Models' by Le et. al [2013]`
    * And why: "This differs from ^. We force all operations to use `atomic_thread_fence(std::memory_order_cst)`. This isn't strictly necessary for the correct internal functioning of some operations. However, by forcing a full memory barrier, we can ensure all data written by a user is visible inside a task. For example:
    
    ```
    int i = 3;
    scheduler->AddTask([&i](){ assert(i == 3); });
    ```

We can get away with option 2, because all tasks go through the queue code. It's a "bit" obfuscating where the synchronization happens, but if we have a bit comment at the top, we should be ok.

Thoughts?
