### ISSUE TITLE
Add ability to use system boost

### ISSUE THREAD

**Issue by egorpugin** [RichieSams/FiberTaskingLib#35]
Hi!

I tried to compile your library with the latest boost 1.63.0 but it does not work out of the box.
Is it possible to provide an alternate way of including boost except that from third party dir?

1. Boost 1.63.0 does not have fcontext.h
2. Namespace `boost_context` is not the default namespace for boost. Should be `boost::context`.

**Comment by RichieSams** [comment]
This library doesn't use boost. Well, not in the traditional sense. It just uses the asm files that implement low level switching of stack and execution contexts. I ripped the asm files out of the boost context sources files and include them separately in third_party for 3 reasons:

1. The boost context API has changed multiple times over the versions, which made it tedious in cmake to detect and force specific versions of boost
2. The library doesn't need any of the other boost library features. Linking to boost on different platforms is really annoying.
3. The API for boost_context in the later versions is a rather different use case than in FiberTaskingLib. By forking, I can keep a singular API and modify it to the FiberTaskingLib use case.


So, to answer your question, no, you can not use Boost 1.63 instead of the modded subset in the third_party folder.

But, then a question for you: What was the error when you tried to compile? I recently upgraded the asm files to roughly 1.63 master branch. Some of the platforms aren't yet modified yet. (ARM being a high contender). I was planning to re-add more platforms this weekend.

**Comment by egorpugin** [comment]
I see.

I tried to integrate your library into my package manager. It handles all stuff (dependencies, different platforms) for you.
So I've added a dependency to boost.context and it failed to build.
https://cppan.org/pvt.cppan.demo.richiesams.fibertaskinglib/version/master/information

In standalone case like yours I have to implement build rules for third_party/boost_context. This violates DRY principle. :) Unnecessary work.

**Comment by RichieSams** [comment]
Ahhhh. 

If you're using cmake, FiberTaskingLib should have no external dependencies. The .h file and the asm files from boost can be considered part of the source files for FiberTaskingLib. I chose to put them in 'third_party' just for clarity reasons. (Licensing, etc.) They are originally written by the boost people, but have been edited by me.

**Comment by egorpugin** [comment]
Well then, I agree this issue is invalid. Sorry for bothering.

ps. FYI I've added necessary rules and it works now from my system.
See spec file - build rules:
https://cppan.org/pvt.cppan.demo.richiesams.fibertaskinglib/version/master/specification

**Comment by RichieSams** [comment]
No worries! :) That's a really nice system you have. I see how the files get added within the specification tab. How is the build called?

Also, I believe you have an error still:
files:
    -   include/.*
    -   source/.*
    -   third_party/boost_context/.*

exclude_from_build:
    -   third_party/boost_context/.*

The boost_context files are both included and excluded from the build

**Comment by egorpugin** [comment]
Try `cppan --build pvt.cppan.demo.richiesams.fibertaskinglib-master`. 
`files` adds files for package. But `exclude_from_build` excludes them only from building because asm files are handled manually.

**Comment by RichieSams** [comment]
Ahhh. Thanks!

**Comment by egorpugin** [comment]
Cppan creates also lightweight packages to fast delivering. So it's not necessary to clone all repo or maybe included tests, scripts etc. Only sources.
