### ISSUE TITLE
Possible issue of item-copy in WaitFreeQueue::Pop and WaitFreeQueue::Steal 

### ISSUE THREAD

**Issue by ChemiaAion** [RichieSams/FiberTaskingLib#68]
Please note that these two will always make a **copy** of the item into `T *value` provided, even when the race was lost:
https://github.com/RichieSams/FiberTaskingLib/blob/0b1aa418990a9dd4ff39904004ac412fbb1a339a/include/ftl/wait_free_queue.h#L138 https://github.com/RichieSams/FiberTaskingLib/blob/0b1aa418990a9dd4ff39904004ac412fbb1a339a/include/ftl/wait_free_queue.h#L169

As far as I can tell this is safe in current implementation, with simple POD `TaskBundle` structure.
What I am worry about is that `CircularArray::Get` returns a **copy** of underlying item instead of thr item itself through reference/pointer, this is then used as `nextTask` in `TaskScheduler::FiberStart`.

**Comment by martty** [comment]
Are you concerned about the performance implications of making a copy, or if TaskBundle becomes a non-POD (correctness)?

**Comment by ChemiaAion** [comment]
Second (in some way), that we have the _true_ item value stored someware in CircularArray self-list, but since we go through WaitFreeQueue::Pop or WaitFreeQueue::Steal we have got the copy not related any more to what is going on with the CircularArray container.

**Comment by ChemiaAion** [comment]
Shortly, `Circular Array::Grow` implemented as-is currently makes no sense IMO, since we are always getting a copies of its contents, so there is no one who is actually touching its content.

**Comment by ChemiaAion** [comment]
Regarding the performance, there are unnecessary item copies down to `Circular Array::Push`, but since `TaskBundle` is POD simple it's not my concern.

Since ftl claim to be depended on C++11 I will try to add some move semantics with emplace approach around `WaitFreeQueue` and above in a next few days...

**Comment by martty** [comment]
If `WaitFreeQueue` stores items with value semantics, returning by copy is correct, as the items don't have further identity than what their value is (`TaskBundle` has value semantics).  `WFQ` does not support returning pointers to the elements, as the only safe operations are `Push`, `Pop` and `Steal`. (eg. returned pointers can point to a new element after another thread Steal`s`). There might be some optimisation opportunity to reduce copies and/or convert them into moves, but as you noted, due to the size and PODness of `TaskBundle`, probably it is not a big win.

Not sure about your comment about `Grow`: underlying `CircularArray`s can be changed by `Push`.
